<#
.SYNOPSIS
    Starts the local dev stack for E2E testing (DynamoDB Local + backend + frontend).

.DESCRIPTION
    1. Starts DynamoDB Local in Docker
    2. Creates the commute-profiles table
    3. Ensures backend/.env points at DynamoDB Local
    4. Ensures frontend/.env.local has auth bypass + local API URL
    5. Starts backend and frontend dev servers in separate windows

    Stop everything afterwards with:  .\Stop-DevStack.ps1

.EXAMPLE
    .\Start-DevStack.ps1
    # Then run E2E tests:  cd frontend; npm run test:e2e
#>

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

# ── Colours ──────────────────────────────────────────────────────────────────
function Write-Step  { param([string]$msg) Write-Host "`n► $msg" -ForegroundColor Cyan }
function Write-OK    { param([string]$msg) Write-Host "  ✓ $msg" -ForegroundColor Green }
function Write-Skip  { param([string]$msg) Write-Host "  - $msg (skipped)" -ForegroundColor Yellow }

# ── 1. DynamoDB Local ────────────────────────────────────────────────────────
Write-Step 'Starting DynamoDB Local'

$existing = docker ps -a --filter "name=dynamodb-local" --format "{{.Names}}" 2>$null
if ($existing -eq 'dynamodb-local') {
    $running = docker ps --filter "name=dynamodb-local" --format "{{.Names}}" 2>$null
    if ($running -eq 'dynamodb-local') {
        Write-Skip 'Container already running'
    } else {
        docker start dynamodb-local | Out-Null
        Write-OK 'Restarted existing container'
    }
} else {
    docker run -d --name dynamodb-local -p 8000:8000 amazon/dynamodb-local | Out-Null
    Write-OK 'Created and started container'
}

# ── 2. Create profiles table (idempotent) ───────────────────────────────────
Write-Step 'Creating commute-profiles table'

$env:AWS_ACCESS_KEY_ID     = 'fakekey'
$env:AWS_SECRET_ACCESS_KEY = 'fakesecret'

# Wait for DynamoDB Local to be ready (Java startup can take a few seconds)
$ready = $false
for ($i = 0; $i -lt 15; $i++) {
    try {
        $raw = aws dynamodb list-tables --endpoint-url http://localhost:8000 --region eu-west-2 --output json 2>$null
        if ($LASTEXITCODE -eq 0 -and $raw) {
            $ready = $true
            break
        }
    } catch {}
    Start-Sleep -Seconds 1
}
if (-not $ready) {
    Write-Host "  ✗ DynamoDB Local not responding after 15 seconds" -ForegroundColor Red
    exit 1
}

$tables = $raw | ConvertFrom-Json
if ($tables -and $tables.TableNames -and ($tables.TableNames -contains 'commute-profiles')) {
    Write-Skip 'Table already exists'
} else {
    aws dynamodb create-table `
        --table-name commute-profiles `
        --attribute-definitions AttributeName=userId,AttributeType=S AttributeName=profileId,AttributeType=S `
        --key-schema AttributeName=userId,KeyType=HASH AttributeName=profileId,KeyType=RANGE `
        --billing-mode PAY_PER_REQUEST `
        --endpoint-url http://localhost:8000 `
        --region eu-west-2 | Out-Null
    Write-OK 'Table created'
}

# ── 3. Backend .env ──────────────────────────────────────────────────────────
Write-Step 'Checking backend/.env'

$backendEnv = Join-Path $root 'backend\.env'
if (Test-Path $backendEnv) {
    $content = Get-Content $backendEnv -Raw
    if ($content -match 'DYNAMODB_ENDPOINT=http://localhost:8000') {
        Write-OK 'backend/.env already configured for local DynamoDB'
    } else {
        Write-Host "  ⚠ backend/.env exists but DYNAMODB_ENDPOINT may not point to localhost:8000" -ForegroundColor Yellow
        Write-Host "    Please verify manually." -ForegroundColor Yellow
    }
} else {
    Copy-Item (Join-Path $root 'backend\.env.example') $backendEnv
    Write-OK 'Copied .env.example → .env (edit API keys if needed)'
}

# ── 4. Frontend .env.local ───────────────────────────────────────────────────
Write-Step 'Configuring frontend/.env.local for local testing'

$frontendEnv = Join-Path $root 'frontend\.env.local'
$localConfig = @'
# Local dev stack — auto-generated by Start-DevStack.ps1
VITE_API_URL=http://localhost:3001
VITE_DEV_BYPASS_AUTH=true
VITE_REDIRECT_URL=http://localhost:5173/callback
VITE_COGNITO_USER_POOL_ID=local
VITE_COGNITO_APP_CLIENT_ID=local
VITE_COGNITO_DOMAIN=local
'@

if (Test-Path $frontendEnv) {
    # Back up existing config
    $backup = "$frontendEnv.bak"
    Copy-Item $frontendEnv $backup -Force
    Write-Host "  Backed up existing .env.local → .env.local.bak" -ForegroundColor Yellow
}
Set-Content -Path $frontendEnv -Value $localConfig -Encoding utf8NoBOM
Write-OK 'frontend/.env.local written (auth bypassed, API → localhost:3001)'

# ── 5. Start dev servers ─────────────────────────────────────────────────────
Write-Step 'Starting backend dev server'
Start-Process powershell -ArgumentList "-NoExit", "-ExecutionPolicy", "Bypass", "-Command", "cd '$root\backend'; npm run dev" -WindowStyle Normal
Write-OK 'Backend starting in new window (http://localhost:3001)'

Write-Step 'Starting frontend dev server'
Start-Process powershell -ArgumentList "-NoExit", "-ExecutionPolicy", "Bypass", "-Command", "cd '$root\frontend'; npm run dev" -WindowStyle Normal
Write-OK 'Frontend starting in new window (http://localhost:5173)'

# ── Done ─────────────────────────────────────────────────────────────────────
Write-Host "`n════════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  Dev stack starting. Wait a few seconds for servers." -ForegroundColor Green
Write-Host "  Then run E2E tests:" -ForegroundColor Green
Write-Host "    cd frontend" -ForegroundColor White
Write-Host "    npm run test:e2e" -ForegroundColor White
Write-Host "" -ForegroundColor Green
Write-Host "  To stop:  .\Stop-DevStack.ps1" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════`n" -ForegroundColor Green
